services:
  collector:
    image: houseplants-collector:latest
    container_name: collector
    ports:
      - 50051:50051
    networks:
      - houseplants-network

networks:
  houseplants-network:
    external: true
