// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.3
// source: sensors.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoistureData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Moisture    int32 `protobuf:"varint,1,opt,name=moisture,proto3" json:"moisture,omitempty"`
	Temperature int32 `protobuf:"varint,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Light       int32 `protobuf:"varint,3,opt,name=light,proto3" json:"light,omitempty"`
}

func (x *MoistureData) Reset() {
	*x = MoistureData{}
	mi := &file_sensors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoistureData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoistureData) ProtoMessage() {}

func (x *MoistureData) ProtoReflect() protoreflect.Message {
	mi := &file_sensors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoistureData.ProtoReflect.Descriptor instead.
func (*MoistureData) Descriptor() ([]byte, []int) {
	return file_sensors_proto_rawDescGZIP(), []int{0}
}

func (x *MoistureData) GetMoisture() int32 {
	if x != nil {
		return x.Moisture
	}
	return 0
}

func (x *MoistureData) GetTemperature() int32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *MoistureData) GetLight() int32 {
	if x != nil {
		return x.Light
	}
	return 0
}

var File_sensors_proto protoreflect.FileDescriptor

var file_sensors_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x62, 0x0a, 0x0c, 0x4d, 0x6f, 0x69,
	0x73, 0x74, 0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x6f, 0x69,
	0x73, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f, 0x69,
	0x73, 0x74, 0x75, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x42, 0x2a, 0x5a,
	0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x64, 0x65, 0x73,
	0x61, 0x69, 0x39, 0x36, 0x2f, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_sensors_proto_rawDescOnce sync.Once
	file_sensors_proto_rawDescData = file_sensors_proto_rawDesc
)

func file_sensors_proto_rawDescGZIP() []byte {
	file_sensors_proto_rawDescOnce.Do(func() {
		file_sensors_proto_rawDescData = protoimpl.X.CompressGZIP(file_sensors_proto_rawDescData)
	})
	return file_sensors_proto_rawDescData
}

var file_sensors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sensors_proto_goTypes = []any{
	(*MoistureData)(nil), // 0: protobuf.MoistureData
}
var file_sensors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sensors_proto_init() }
func file_sensors_proto_init() {
	if File_sensors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sensors_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sensors_proto_goTypes,
		DependencyIndexes: file_sensors_proto_depIdxs,
		MessageInfos:      file_sensors_proto_msgTypes,
	}.Build()
	File_sensors_proto = out.File
	file_sensors_proto_rawDesc = nil
	file_sensors_proto_goTypes = nil
	file_sensors_proto_depIdxs = nil
}
