services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
      - ../../certs:/certs
    ports:
      - 8883:8883
    networks:
      - houseplants-network

networks:
  houseplants-network:
    external: true
